image: maven:3.8-openjdk-17

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - checkstyle


build:
  stage: build
  script:
    - mvn -D"maven.test.skip=true" clean package -pl rosetta-xcore-plugin-dependencies,rosetta-lang,rosetta-testing,com.regnosys.rosetta.interpreternew

test-jdk17:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report -pl rosetta-xcore-plugin-dependencies,rosetta-lang,rosetta-testing,com.regnosys.rosetta.interpreternew
    - cat com.regnosys.rosetta.interpreternew/target/site/jacoco/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
  coverage: /TestCoverage:(\d+)%/

checkstyle:
  stage: checkstyle
  script:
    - mvn checkstyle:check -pl com.regnosys.rosetta.interpreternew

